### ISSUE TITLE
Using block 0 with Xread

### ISSUE THREAD

**Issue by gam-phon** [stfnmllr/go-resp3#1]
Thank you for your great library.

I want to use `block 0` with `Xread`
How can I handle blocking?

In this example, It is not blocking
```
m, _ := conn.Xread(client.Int64Ptr(20), client.Int64Ptr(0), []interface{}{"key:1"}, []string{"0-0"}).ToXread()
fmt.Println(m)
```

**Comment by stfnmllr** [comment]
> Thank you for your great library.
You are welcome!
In regards to the issue:
- would be nice if you are going to provide a complete example next time and
- please do not ignore the potential returned error and
- please double check if possible potential issues in e.g. redis-cli first
Anyway,
- count is only an upper limit, so
- the command will only block, if
- no data was added to the stream at all as the starting point is "0-0"
Changing the id to e.g. "$" should block.

**Comment by gam-phon** [comment]
Thank you so much @stfnmllr 
Yes it is blocking using `$`
