### ISSUE TITLE
Type of Items in XItem

### ISSUE THREAD

**Issue by gam-phon** [stfnmllr/go-resp3#3]
I am using ToXread with Xreadgroup
```
m, _ := conn.Xreadgroup().ToXread()
```
m["streamName"] will be "[]XItem", here is the struct of XItem:
```
type XItem struct {
	ID    string
	Items []string
}
```
Items will be like this: []string{"field1", "value1", "field2", "value2", "field3", "value3"}.
I think, Items should be of type `[]MapItem` or `map[string]string`  instead of `[]string`. Then you can extract key and value easily.
What do you think?

**Comment by stfnmllr** [comment]
I do understand the request and if I am not wrong, the 'key value' pairs were provided as map by Redis in 6 beta. But it got changed before 6 release.
If you double check on the redis-cli response, e.g.:
```
redis-cli> hello 3
1# "server" => "redis"
2# "version" => "6.0.5"
3# "proto" => (integer) 3
4# "id" => (integer) 4
5# "mode" => "standalone"
6# "role" => "master"
7# "modules" => (empty array)
redis-cli> xgroup create mystream mygroup $
OK
redis-cli> XADD mystream * name Sara surname OConnor
"1594118611872-0"
redis-cli> XADD mystream * name Billie surname Eilish
"1594118616887-0"
redis-cli> xreadgroup group mygroup test streams mystream >
1# "mystream" => 1) 1) "1594118611872-0"
      2) 1) "name"
         2) "Sara"
         3) "surname"
         4) "OConnor"
   2) 1) "1594118616887-0"
      2) 1) "name"
         2) "Billie"
         3) "surname"
         4) "Eilish"
```
Like you can see,  the 'key value' pairs are returned as a list, not a map. It's even like the 'key' is not forced to be unique:

```
redis-cli> XADD mystream * name Sara surname OConnor name lenny
"1594118933239-0"
redis-cli> xreadgroup group mygroup test streams mystream >
1# "mystream" => 1) 1) "1594118933239-0"
      2) 1) "name"
         2) "Sara"
         3) "surname"
         4) "OConnor"
         5) "name"
         6) "lenny"
```

**Comment by gam-phon** [comment]
Thank you for your clarification
