### ISSUE TITLE
when i use bcast i got err with two "prefix" params

### ISSUE THREAD

**Issue by lee123456780** [stfnmllr/go-resp3#5]
I change the code like this ,and anything is ok 
github.com\stfnmllr\go-resp3\client\command_gen.go @1019
if prefix != nil {
		for _, v := range prefix {
			r.request.cmd = append(r.request.cmd, "PREFIX")
			r.request.cmd = append(r.request.cmd, v)
		}
	}

**Comment by stfnmllr** [comment]
Yes, the generated code for the client tracking command using prefixes is not correct. We are going to provide a fix as soon as possible.

**Comment by stfnmllr** [comment]
Should be fixed with https://github.com/stfnmllr/go-resp3/releases/tag/v0.11.4.
